#include "instructionswidget.h"
#include "loadprogramdialogue.h"
#include "ui_loadprogramdialogue.h"

LoadProgramDialogue::LoadProgramDialogue(QWidget *parent) :
    QDialog(parent), ui(new Ui::LoadProgramDialogue) {
    ui->setupUi(this);

    ui->horizontalLayout->addWidget(new InstructionsWidget(this));
}

LoadProgramDialogue::~LoadProgramDialogue() {
    delete ui;
}

QString LoadProgramDialogue::getProgramCode() {
    return ui->txtMemory->toPlainText();
}

void LoadProgramDialogue::on_comboExamples_currentIndexChanged(int index) {
    if (index == 1) {
        ui->txtMemory->setPlainText("LOAD  0x05\n"
                                    "ADD   0x06\n"
                                    "STORE 0x07\n"
                                    "STOP\n"
                                    "\n"
                                    "54\n"
                                    "46\n");
    } else if (index == 2) {
        ui->txtMemory->setPlainText("LOAD  0x05\n"
                                    "ADD   0x06\n"
                                    "STORE 0x07\n"
                                    "JUMP  0x01\n"
                                    "\n"
                                    "0\n"
                                    "1\n");
    } else if (index == 3) {
        ui->txtMemory->setPlainText("LOAD  0x82\n"
                                    "STORE 0x81\n"
                                    "LOAD  0x81\n"
                                    "ADD   0x82\n"
                                    "STORE 0x81\n"
                                    "SUB   0x80\n"
                                    "BRZ   0x40\n"
                                    "LOAD  0x80\n"
                                    "SUB   0x81\n"
                                    "BRZ   0x20\n"
                                    "BRN   0x02\n"
                                    "JUMP  0x08\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "LOAD  0x83\n"
                                    "STORE 0x84\n"
                                    "STOP\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "LOAD  0x82\n"
                                    "STORE 0x84\n"
                                    "STOP\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "0\n"
                                    "5\n"
                                    "1\n"
                                    "1\n"
                                    "0\n"
                                    "0\n"
                                    "\n"
                                    "0x80 = Number to test\n"
                                    "0x84 = Result (1 = true)");
    }
}
